---

- hosts: all
  become: true
  tasks:
  - name: update repository index
    yum:
      update_cache: yes

  - name: install apache/httpd package
    yum:
      name: httpd
      state: absent

  - name: app php support
    yum:
      name: php-fpm
      state: absent
        
